
name: RideLink



options:
settings:
    IPHONEOS_DEPLOYMENT_TARGET: 17.0

include:
  - packages.yml
  - UICore/config.yml
  - CommunicationsCore/config.yml
  - App/config.yml
  - AppNotificationExtension/config.yml
